/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import model.Public;
import model.tables.records.VLabelReservationRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelReservation extends TableImpl<VLabelReservationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.v_label_reservation</code>
     */
    public static final VLabelReservation V_LABEL_RESERVATION = new VLabelReservation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VLabelReservationRecord> getRecordType() {
        return VLabelReservationRecord.class;
    }

    /**
     * The column <code>public.v_label_reservation.id</code>.
     */
    public final TableField<VLabelReservationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reservation.title</code>.
     */
    public final TableField<VLabelReservationRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.v_label_reservation.date_start</code>.
     */
    public final TableField<VLabelReservationRecord, LocalDateTime> DATE_START = createField(DSL.name("date_start"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_reservation.date_end</code>.
     */
    public final TableField<VLabelReservationRecord, LocalDateTime> DATE_END = createField(DSL.name("date_end"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.v_label_reservation.id_workspace</code>.
     */
    public final TableField<VLabelReservationRecord, Integer> ID_WORKSPACE = createField(DSL.name("id_workspace"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_label_reservation.workspace</code>.
     */
    public final TableField<VLabelReservationRecord, String> WORKSPACE = createField(DSL.name("workspace"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.v_label_reservation.color</code>.
     */
    public final TableField<VLabelReservationRecord, String> COLOR = createField(DSL.name("color"), SQLDataType.VARCHAR(50), this, "");

    private VLabelReservation(Name alias, Table<VLabelReservationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VLabelReservation(Name alias, Table<VLabelReservationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "v_label_reservation" as  SELECT r.id,
         r.title,
         r.date_start,
         r.date_end,
         r.id_workspace,
         w.label AS workspace,
         w.color
        FROM (reservation r
          JOIN workspace w ON ((r.id_workspace = w.id)));
        """), where);
    }

    /**
     * Create an aliased <code>public.v_label_reservation</code> table reference
     */
    public VLabelReservation(String alias) {
        this(DSL.name(alias), V_LABEL_RESERVATION);
    }

    /**
     * Create an aliased <code>public.v_label_reservation</code> table reference
     */
    public VLabelReservation(Name alias) {
        this(alias, V_LABEL_RESERVATION);
    }

    /**
     * Create a <code>public.v_label_reservation</code> table reference
     */
    public VLabelReservation() {
        this(DSL.name("v_label_reservation"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public VLabelReservation as(String alias) {
        return new VLabelReservation(DSL.name(alias), this);
    }

    @Override
    public VLabelReservation as(Name alias) {
        return new VLabelReservation(alias, this);
    }

    @Override
    public VLabelReservation as(Table<?> alias) {
        return new VLabelReservation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReservation rename(String name) {
        return new VLabelReservation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReservation rename(Name name) {
        return new VLabelReservation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VLabelReservation rename(Table<?> name) {
        return new VLabelReservation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReservation where(Condition condition) {
        return new VLabelReservation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReservation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReservation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReservation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReservation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReservation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReservation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VLabelReservation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReservation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VLabelReservation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
