/*
 * This file is generated by jOOQ.
 */
package model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import model.Keys;
import model.Public;
import model.tables.Reservation.ReservationPath;
import model.tables.records.WorkspaceRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Workspace extends TableImpl<WorkspaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.workspace</code>
     */
    public static final Workspace WORKSPACE = new Workspace();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkspaceRecord> getRecordType() {
        return WorkspaceRecord.class;
    }

    /**
     * The column <code>public.workspace.id</code>.
     */
    public final TableField<WorkspaceRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.workspace.label</code>.
     */
    public final TableField<WorkspaceRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.workspace.color</code>.
     */
    public final TableField<WorkspaceRecord, String> COLOR = createField(DSL.name("color"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Workspace(Name alias, Table<WorkspaceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Workspace(Name alias, Table<WorkspaceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.workspace</code> table reference
     */
    public Workspace(String alias) {
        this(DSL.name(alias), WORKSPACE);
    }

    /**
     * Create an aliased <code>public.workspace</code> table reference
     */
    public Workspace(Name alias) {
        this(alias, WORKSPACE);
    }

    /**
     * Create a <code>public.workspace</code> table reference
     */
    public Workspace() {
        this(DSL.name("workspace"), null);
    }

    public <O extends Record> Workspace(Table<O> path, ForeignKey<O, WorkspaceRecord> childPath, InverseForeignKey<O, WorkspaceRecord> parentPath) {
        super(path, childPath, parentPath, WORKSPACE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WorkspacePath extends Workspace implements Path<WorkspaceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WorkspacePath(Table<O> path, ForeignKey<O, WorkspaceRecord> childPath, InverseForeignKey<O, WorkspaceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WorkspacePath(Name alias, Table<WorkspaceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WorkspacePath as(String alias) {
            return new WorkspacePath(DSL.name(alias), this);
        }

        @Override
        public WorkspacePath as(Name alias) {
            return new WorkspacePath(alias, this);
        }

        @Override
        public WorkspacePath as(Table<?> alias) {
            return new WorkspacePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<WorkspaceRecord, Integer> getIdentity() {
        return (Identity<WorkspaceRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WorkspaceRecord> getPrimaryKey() {
        return Keys.WORKSPACE_PKEY;
    }

    @Override
    public List<UniqueKey<WorkspaceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.WORKSPACE_COLOR_KEY, Keys.WORKSPACE_LABEL_KEY);
    }

    private transient ReservationPath _reservation;

    /**
     * Get the implicit to-many join path to the <code>public.reservation</code>
     * table
     */
    public ReservationPath reservation() {
        if (_reservation == null)
            _reservation = new ReservationPath(this, null, Keys.RESERVATION__RESERVATION_ID_WORKSPACE_FKEY.getInverseKey());

        return _reservation;
    }

    @Override
    public Workspace as(String alias) {
        return new Workspace(DSL.name(alias), this);
    }

    @Override
    public Workspace as(Name alias) {
        return new Workspace(alias, this);
    }

    @Override
    public Workspace as(Table<?> alias) {
        return new Workspace(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Workspace rename(String name) {
        return new Workspace(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Workspace rename(Name name) {
        return new Workspace(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Workspace rename(Table<?> name) {
        return new Workspace(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workspace where(Condition condition) {
        return new Workspace(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workspace where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workspace where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workspace where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Workspace where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Workspace where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Workspace where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Workspace where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workspace whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Workspace whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
