/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Reservation;
import model.tables.Workspace;
import model.tables.records.ReservationRecord;
import model.tables.records.WorkspaceRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ReservationRecord> RESERVATION_PKEY = Internal.createUniqueKey(Reservation.RESERVATION, DSL.name("reservation_pkey"), new TableField[] { Reservation.RESERVATION.ID }, true);
    public static final UniqueKey<WorkspaceRecord> WORKSPACE_COLOR_KEY = Internal.createUniqueKey(Workspace.WORKSPACE, DSL.name("workspace_color_key"), new TableField[] { Workspace.WORKSPACE.COLOR }, true);
    public static final UniqueKey<WorkspaceRecord> WORKSPACE_LABEL_KEY = Internal.createUniqueKey(Workspace.WORKSPACE, DSL.name("workspace_label_key"), new TableField[] { Workspace.WORKSPACE.LABEL }, true);
    public static final UniqueKey<WorkspaceRecord> WORKSPACE_PKEY = Internal.createUniqueKey(Workspace.WORKSPACE, DSL.name("workspace_pkey"), new TableField[] { Workspace.WORKSPACE.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ReservationRecord, WorkspaceRecord> RESERVATION__RESERVATION_ID_WORKSPACE_FKEY = Internal.createForeignKey(Reservation.RESERVATION, DSL.name("reservation_id_workspace_fkey"), new TableField[] { Reservation.RESERVATION.ID_WORKSPACE }, Keys.WORKSPACE_PKEY, new TableField[] { Workspace.WORKSPACE.ID }, true);
}
