/*
 * This file is generated by jOOQ.
 */
package model;


import java.util.Arrays;
import java.util.List;

import model.tables.Reservation;
import model.tables.VLabelReservation;
import model.tables.Workspace;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.reservation</code>.
     */
    public final Reservation RESERVATION = Reservation.RESERVATION;

    /**
     * The table <code>public.v_label_reservation</code>.
     */
    public final VLabelReservation V_LABEL_RESERVATION = VLabelReservation.V_LABEL_RESERVATION;

    /**
     * The table <code>public.workspace</code>.
     */
    public final Workspace WORKSPACE = Workspace.WORKSPACE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Reservation.RESERVATION,
            VLabelReservation.V_LABEL_RESERVATION,
            Workspace.WORKSPACE
        );
    }
}
