/*
 * This file is generated by jOOQ.
 */
package model;


import model.tables.Reservation;
import model.tables.VLabelReservation;
import model.tables.Workspace;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.reservation</code>.
     */
    public static final Reservation RESERVATION = Reservation.RESERVATION;

    /**
     * The table <code>public.v_label_reservation</code>.
     */
    public static final VLabelReservation V_LABEL_RESERVATION = VLabelReservation.V_LABEL_RESERVATION;

    /**
     * The table <code>public.workspace</code>.
     */
    public static final Workspace WORKSPACE = Workspace.WORKSPACE;
}
