/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDateTime;

import model.tables.Reservation;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReservationRecord extends UpdatableRecordImpl<ReservationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reservation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reservation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.reservation.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reservation.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.reservation.date_start</code>.
     */
    public void setDateStart(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reservation.date_start</code>.
     */
    public LocalDateTime getDateStart() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.reservation.date_end</code>.
     */
    public void setDateEnd(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.reservation.date_end</code>.
     */
    public LocalDateTime getDateEnd() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.reservation.id_workspace</code>.
     */
    public void setIdWorkspace(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.reservation.id_workspace</code>.
     */
    public Integer getIdWorkspace() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationRecord
     */
    public ReservationRecord() {
        super(Reservation.RESERVATION);
    }

    /**
     * Create a detached, initialised ReservationRecord
     */
    public ReservationRecord(Integer id, String title, LocalDateTime dateStart, LocalDateTime dateEnd, Integer idWorkspace) {
        super(Reservation.RESERVATION);

        setId(id);
        setTitle(title);
        setDateStart(dateStart);
        setDateEnd(dateEnd);
        setIdWorkspace(idWorkspace);
        resetChangedOnNotNull();
    }
}
