/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import java.time.LocalDateTime;

import model.tables.VLabelReservation;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VLabelReservationRecord extends TableRecordImpl<VLabelReservationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_label_reservation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_label_reservation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_label_reservation.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_label_reservation.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_label_reservation.date_start</code>.
     */
    public void setDateStart(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_label_reservation.date_start</code>.
     */
    public LocalDateTime getDateStart() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.v_label_reservation.date_end</code>.
     */
    public void setDateEnd(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_label_reservation.date_end</code>.
     */
    public LocalDateTime getDateEnd() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.v_label_reservation.id_workspace</code>.
     */
    public void setIdWorkspace(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_label_reservation.id_workspace</code>.
     */
    public Integer getIdWorkspace() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.v_label_reservation.workspace</code>.
     */
    public void setWorkspace(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_label_reservation.workspace</code>.
     */
    public String getWorkspace() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_label_reservation.color</code>.
     */
    public void setColor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_label_reservation.color</code>.
     */
    public String getColor() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VLabelReservationRecord
     */
    public VLabelReservationRecord() {
        super(VLabelReservation.V_LABEL_RESERVATION);
    }

    /**
     * Create a detached, initialised VLabelReservationRecord
     */
    public VLabelReservationRecord(Integer id, String title, LocalDateTime dateStart, LocalDateTime dateEnd, Integer idWorkspace, String workspace, String color) {
        super(VLabelReservation.V_LABEL_RESERVATION);

        setId(id);
        setTitle(title);
        setDateStart(dateStart);
        setDateEnd(dateEnd);
        setIdWorkspace(idWorkspace);
        setWorkspace(workspace);
        setColor(color);
        resetChangedOnNotNull();
    }
}
