/*
 * This file is generated by jOOQ.
 */
package model.tables.records;


import model.tables.Workspace;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkspaceRecord extends UpdatableRecordImpl<WorkspaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.workspace.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.workspace.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.workspace.label</code>.
     */
    public void setLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.workspace.label</code>.
     */
    public String getLabel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.workspace.color</code>.
     */
    public void setColor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.workspace.color</code>.
     */
    public String getColor() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkspaceRecord
     */
    public WorkspaceRecord() {
        super(Workspace.WORKSPACE);
    }

    /**
     * Create a detached, initialised WorkspaceRecord
     */
    public WorkspaceRecord(Integer id, String label, String color) {
        super(Workspace.WORKSPACE);

        setId(id);
        setLabel(label);
        setColor(color);
        resetChangedOnNotNull();
    }
}
